# Makefile dla Programowanie Obiektowe 1
# Filip Kania

FLAGS = -Wall -g
#RM = rm -f

PROG = Lab04
FILE = lab04.cpp Variable.cpp

all: $(FILE)
	g++ $(FLAGS) -o $(PROG) $(FILE)

val: 
	valgrind ./Lab04

run:
	clear
	./Lab04
